name=ESPNowMesh
version=0.0.0
author=Kevin Kao <k329272@gmail.com>
maintainer=Kevin Kao <k329272@gmail.com>
sentence=ESP-NOW routing for WiFi wakeups; Energy efficient, lower latency
paragraph=Implements ESP-NOW routing via Dijkstra, then wakes up wifi nodes for higher throughput
category=Communication
architectures=esp32
url=https://github.com/k329272/PLEXUS-NOW
includes=
depends=